### ISSUE TITLE
Xcode 7 Bitcode Enabled

### ISSUE THREAD

**Issue by aplourde** [AxonixRTB/axonix-ios-sdk-releases#2]
Hi !
Can you please repackage a new version of the iOS sdk with Bitcode enabled, which is mandatory to benefit of Apple's App Thinning technology.

https://developer.apple.com/library/prerelease/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

Thanks

**Comment by osuka** [comment]
Hi, we are working on this, but we need to test it and ensure that doesn't break backwards compatibility for applications still reliant on older versions of XCode. Will post and update here when we have it ready.

**Comment by aplourde** [comment]
Nice ! Thank you !
